### ISSUE TITLE
пробовали что то ничего не прислал

### ISSUE THREAD

**Issue by girs1982** [K3rnel-Dev/TelegramStealer#1]
указали группу и бот токен, но ничего не пришло(

**Comment by K3rnel-Dev** [comment]
Здравствуй, нужно указывать не id группы а свой личный chatID, алгоритм работы программы прост:
1) Вы создаете бота в @BotFather и запускаете чат с ним(чтобы архив приходил).
2) Вы узнаете свой личный chatid так как бот напрямую вам же и высылает архив, id можно получить в @getmy_idbot
3) Создаете готовый билд со всеми этими настройками(учитывайте чтобы личный диалог был запущен с ботом)

Если у вас все еще не получается напишите в этой ветке.

**Comment by girs1982** [comment]
> Здравствуй, нужно указывать не id группы а свой личный chatID, алгоритм работы программы прост:
> 
> 1. Вы создаете бота в "BotFather" и запускаете чат с ним(чтобы архив приходил).
> 2. Вы узнаете свой личный chatid так как бот напрямую вам же и высылает архив, id можно получить в @getmy_idbot
> 3. Создаете готовый билд со всеми этими настройками(учитывайте чтобы личный диалог был запущен с ботом)
> 
> Если у вас все еще не получается напишите в этой ветке.

так тоже пробовал, ничего

**Comment by K3rnel-Dev** [comment]
Скажите мне путь до телеграмма находится не в стандартной(дефолтной) директории которая указывалась при ее установке?, если просмотреть исходник стаба, вы можете заметить что код проверяет лишь по *известным* директориям, если же он не находит по данным путям он попросту самоудаляеться. В будущем я исправлю эти недочеты.

Это предположение у меня вызвано тем что я только что проверил и у меня идут данные сессии в заархивированном формате.

Скорее всего я предполагаю из за следующих возникших проблем:
1) Tdata папки не существует либо она пустая
2) Путь до телеграмм-папки не стандартный и не находится в списке для проверки стаба

**Comment by girs1982** [comment]
> Скажите мне путь до телеграмма находится не в стандартной(дефолтной) директории которая указывалась при ее установке?, если просмотреть исходник стаба, вы можете заметить что код проверяет лишь по _известным_ директориям, если же он не находит по данным путям он попросту самоудаляеться. В будущем я исправлю эти недочеты.
> 
> Это предположение у меня вызвано тем что я только что проверил и у меня идут данные сессии в заархивированном формате.
> 
> Скорее всего я предполагаю из за следующих возникших проблем:
> 
> 1. Tdata папки не существует либо она пустая
> 2. Путь до телеграмм-папки не стандартный и не находится в списке для проверки стаба

да скорее всего Дуров пофиксил это дело, тг на под опытном был

**Comment by K3rnel-Dev** [comment]
На самом деле это все еще работает), все аккаунты невзирая на 2fa и облачные пароли хранятся в папке tdata с авторизационными данными.

**Comment by girs1982** [comment]
значит надо добавить в код поиск папки, потомучто у нас на свежей установке ничего не пришло

**Comment by K3rnel-Dev** [comment]
Я буду работать над этим. Просто кроме этого проекта я работаю еще над другими.
В скором времени сделаю патч.
